"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import JSZip from "jszip";
import {generateBundle,parseClashYaml,parseManualNode,parseShareLinks,type InputKind,type ListenerType,type ParsedNode} from "@multiport/core";
type Lang="zh"|"en";
const I={
zh:{privacy:"仅在浏览器本地处理",docs:"使用文档",eyebrow:"MIHOMO 多端口配置生成器 · V0.2",title:<>把代理节点变成<br/><em>清晰的本地端口。</em></>,intro:"将 Clash/Mihomo 配置或分享链接转换成“一节点一端口”的 Mihomo 配置，并生成 PortPilot 可导入的 HTTP 与 SOCKS5 档案。节点密钥不会离开此浏览器。",input:"输入",links:"分享链接",yp:"粘贴 Clash / Mihomo YAML 配置……",lp:"每行粘贴一个分享链接……",upload:"上传文件",demo:"使用示例",parse:"解析节点",map:"端口映射",selected:"个已选",start:"起始端口",host:"监听地址",listener:"监听类型",empty:"解析后，节点会显示在这里。",multi:"多端口监听",chain:"链式代理",jump:"跳板节点 B",exit:"出口节点 A",manual:"手工添加节点（YAML）",add:"添加到节点列表",export:"导出",exportTitle:<>两个文件，<br/>一份稳定映射。</>,exportIntro:"Mihomo 配置与浏览器档案使用相同的节点顺序和端口。下载前可以直接阅读完整内容。",yamlHelp:"包含代理节点和独立本地 listeners，可直接交给 Mihomo。",jsonHelp:"只含本地端口映射，不包含上游 UUID、密码或服务器地址。",preview:"文件预览",previewEmpty:"解析并选择节点后显示完整内容",copy:"复制",download:"下载",bundle:"下载完整压缩包",ready:"等待本地输入",local:"无遥测 · 无上传",loaded:"已载入",none:"未找到可用节点",read:"已读取",copied:"已复制",added:"已添加"},
en:{privacy:"Local-only browser processing",docs:"Documentation",eyebrow:"MIHOMO MULTI-PORT CONFIG FORGE · V0.2",title:<>Turn proxy nodes into<br/><em>clean local ports.</em></>,intro:"Convert Clash/Mihomo configurations or share links into one-node-per-port Mihomo listeners and HTTP/SOCKS5 profiles for PortPilot. Node secrets never leave this browser.",input:"Input",links:"Share links",yp:"Paste a Clash / Mihomo YAML configuration…",lp:"Paste one share link per line…",upload:"Upload file",demo:"Use demo",parse:"Parse nodes",map:"Port map",selected:"selected",start:"Start port",host:"Listen host",listener:"Listener type",empty:"Parsed nodes will appear here.",multi:"Multi-port listeners",chain:"Dialer proxy",jump:"Jump node B",exit:"Exit node A",manual:"Add a node manually (YAML)",add:"Add to node list",export:"Export",exportTitle:<>Two files.<br/>One stable map.</>,exportIntro:"The Mihomo configuration and browser profiles share the same node order and ports. Read the complete output before downloading.",yamlHelp:"Contains proxy nodes and independent local listeners, ready for Mihomo.",jsonHelp:"Contains local port mappings only—never upstream UUIDs, passwords, or server addresses.",preview:"File preview",previewEmpty:"Parse and select nodes to display the complete output",copy:"Copy",download:"Download",bundle:"Download complete bundle",ready:"Ready for local input",local:"No telemetry · No uploads",loaded:"Loaded",none:"No usable nodes found",read:"Read",copied:"copied",added:"Added"}
} as const;
const DEMO=`proxies:\n  - name: Demo VLESS\n    type: vless\n    server: example.com\n    port: 443\n    uuid: 00000000-0000-0000-0000-000000000001\n    tls: true\n  - name: Demo SOCKS\n    type: socks5\n    server: 127.0.0.1\n    port: 1080`;
function save(name:string,data:BlobPart,type:string){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),0)}
function initialLanguage():Lang{if(typeof window==="undefined")return "zh";const saved=localStorage.getItem("multiport-language");if(saved==="zh"||saved==="en")return saved;return navigator.language.toLowerCase().startsWith("zh")?"zh":"en"}
export default function Home(){
 const [lang,setLang]=useState<Lang>(initialLanguage),[kind,setKind]=useState<InputKind>("clash"),[source,setSource]=useState(""),[nodes,setNodes]=useState<ParsedNode[]>([]),[selected,setSelected]=useState<Set<string>>(new Set()),[issues,setIssues]=useState<{line?:number;message:string}[]>([]),[startPort,setStartPort]=useState(42000),[host,setHost]=useState("127.0.0.1"),[listenerType,setListenerType]=useState<ListenerType>("mixed"),[baseConfig,setBaseConfig]=useState<Record<string,unknown>>(),[mode,setMode]=useState<"listeners"|"dialer-proxy">("listeners"),[jumpNodeId,setJumpNodeId]=useState(""),[exitNodeId,setExitNodeId]=useState(""),[manual,setManual]=useState("name: Manual SOCKS\ntype: socks5\nserver: 127.0.0.1\nport: 1080"),[notice,setNotice]=useState("");
 const fileRef=useRef<HTMLInputElement>(null),t=I[lang],chosen=useMemo(()=>nodes.filter(n=>selected.has(n.id)),[nodes,selected]);
 useEffect(()=>{document.documentElement.lang=lang==="zh"?"zh-CN":"en";localStorage.setItem("multiport-language",lang)},[lang]);
 const bundle=useMemo(()=>{try{return chosen.length?generateBundle(chosen,{startPort,host,listenerType,baseConfig,mode,jumpNodeId,exitNodeId}):null}catch{return null}},[chosen,startPort,host,listenerType,baseConfig,mode,jumpNodeId,exitNodeId]);
 function parse(value=source,inputKind=kind){const r=inputKind==="clash"?parseClashYaml(value):parseShareLinks(value);setNodes(r.nodes);setBaseConfig(r.baseConfig);setIssues(r.issues);setSelected(new Set(r.nodes.map(n=>n.id)));setJumpNodeId(r.nodes[0]?.id||"");setExitNodeId(r.nodes[1]?.id||"");setNotice(r.nodes.length?`${t.loaded} ${r.nodes.length}`:t.none)}
 async function openFile(file?:File){if(!file)return;const value=await file.text();setSource(value);parse(value);setNotice(`${t.read} ${file.name}`)}
 function add(){try{const n=parseManualNode(manual);setNodes(v=>[...v.filter(x=>x.id!==n.id),n]);setSelected(v=>new Set([...v,n.id]));setNotice(`${t.added} ${n.name}`)}catch(e){setNotice(e instanceof Error?e.message:String(e))}}
 async function copy(value:string,label:string){await navigator.clipboard.writeText(value);setNotice(`${label} ${t.copied}`)}
 async function zip(){if(!bundle)return;const z=new JSZip();z.file("mihomo.yaml",bundle.mihomoYaml);z.file("browser-profiles.json",JSON.stringify(bundle.extensionManifest,null,2));save("multiport-proxy-bundle.zip",await z.generateAsync({type:"blob"}),"application/zip")}
 return <main id="top"><header className="topbar"><a className="brand" href="#top"><b>M</b>MULTIPORT</a><div className="privacy"><i/>{t.privacy}</div><nav><div className="lang"><button className={lang==="zh"?"active":""} onClick={()=>setLang("zh")}>中文</button><button className={lang==="en"?"active":""} onClick={()=>setLang("en")}>EN</button></div><a className="docs" href={lang==="zh"?"https://github.com/huades/MultiPort-Proxy/blob/main/README.zh-CN.md":"https://github.com/huades/MultiPort-Proxy#readme"} target="_blank" rel="noreferrer">{t.docs} ↗</a></nav></header>
 <section className="hero"><div><p className="eyebrow">{t.eyebrow}</p><h1>{t.title}</h1></div><p className="intro">{t.intro}</p></section>
 <section className="workspace"><div className="panel inputPanel"><div className="panelHead"><span>01 / {t.input}</span><span>{kind==="clash"?"YAML":"URI"}</span></div><div className="tabs"><button className={kind==="clash"?"active":""} onClick={()=>setKind("clash")}>Clash YAML</button><button className={kind==="share-links"?"active":""} onClick={()=>setKind("share-links")}>{t.links}</button></div><textarea value={source} onChange={e=>setSource(e.target.value)} placeholder={kind==="clash"?t.yp:t.lp} spellCheck={false}/><input ref={fileRef} hidden type="file" accept=".yaml,.yml,.txt" onChange={e=>void openFile(e.target.files?.[0])}/><div className="actions"><button onClick={()=>fileRef.current?.click()}>{t.upload}</button><button onClick={()=>{setKind("clash");setSource(DEMO);parse(DEMO,"clash")}}>{t.demo}</button><button className="primary" onClick={()=>parse()}>{t.parse} →</button></div>{issues.length>0&&<div className="issues" role="alert">{issues.slice(0,6).map((x,i)=><p key={i}>{x.line?`Line ${x.line}: `:""}{x.message}</p>)}</div>}<details className="manual"><summary>{t.manual}</summary><textarea value={manual} onChange={e=>setManual(e.target.value)} spellCheck={false}/><button onClick={add}>{t.add}</button></details></div>
 <div className="panel"><div className="panelHead"><span>02 / {t.map}</span><span>{chosen.length}/{nodes.length} {t.selected}</span></div><div className="modeSwitch"><button className={mode==="listeners"?"active":""} onClick={()=>setMode("listeners")}>{t.multi}</button><button className={mode==="dialer-proxy"?"active":""} onClick={()=>setMode("dialer-proxy")}>{t.chain}</button></div>{mode==="listeners"?<div className="controls"><label>{t.start}<input type="number" min="1" max="65535" value={startPort} onChange={e=>setStartPort(Number(e.target.value))}/></label><label>{t.host}<input value={host} onChange={e=>setHost(e.target.value)}/></label><label>{t.listener}<select value={listenerType} onChange={e=>setListenerType(e.target.value as ListenerType)}><option>mixed</option><option>http</option><option>socks</option></select></label></div>:<div className="chainControls"><label>{t.jump}<select value={jumpNodeId} onChange={e=>setJumpNodeId(e.target.value)}>{chosen.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></label><span>→</span><label>{t.exit}<select value={exitNodeId} onChange={e=>setExitNodeId(e.target.value)}>{chosen.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></label></div>}<div className="nodeList">{!nodes.length&&<div className="empty">◎<small>{t.empty}</small></div>}{nodes.map((n,i)=><label className="node" key={n.id}><input type="checkbox" checked={selected.has(n.id)} onChange={e=>{const v=new Set(selected);if(e.target.checked)v.add(n.id);else v.delete(n.id);setSelected(v)}}/><span>{String(i+1).padStart(2,"0")}</span><strong>{n.name}<small>{n.type}</small></strong><code>{mode==="listeners"&&selected.has(n.id)?startPort+chosen.findIndex(x=>x.id===n.id):"—"}</code></label>)}</div></div></section>
 <section className="export"><div><span>03 / {t.export}</span><h2>{t.exportTitle}</h2><p>{t.exportIntro}</p></div><div><div className="cards"><article><b>YAML</b><h3>mihomo.yaml</h3><p>{t.yamlHelp}</p><div><button disabled={!bundle} onClick={()=>bundle&&void copy(bundle.mihomoYaml,"YAML")}>{t.copy}</button><button disabled={!bundle} onClick={()=>bundle&&save("mihomo.yaml",bundle.mihomoYaml,"text/yaml")}>{t.download} →</button></div></article><article><b>JSON</b><h3>browser-profiles.json</h3><p>{t.jsonHelp}</p><div><button disabled={!bundle} onClick={()=>bundle&&void copy(JSON.stringify(bundle.extensionManifest,null,2),"JSON")}>{t.copy}</button><button disabled={!bundle} onClick={()=>bundle&&save("browser-profiles.json",JSON.stringify(bundle.extensionManifest,null,2),"application/json")}>{t.download} →</button></div></article></div><div className="previews"><section><header><b>YAML</b><span>{t.preview} · mihomo.yaml</span></header><pre><code>{bundle?.mihomoYaml||t.previewEmpty}</code></pre></section><section><header><b>JSON</b><span>{t.preview} · browser-profiles.json</span></header><pre><code>{bundle?JSON.stringify(bundle.extensionManifest,null,2):t.previewEmpty}</code></pre></section></div><button className="zip" disabled={!bundle} onClick={()=>void zip()}>{t.bundle}<span>.ZIP</span></button></div></section>
 <footer><span>MULTIPORT-PROXY / OPEN SOURCE</span><span aria-live="polite">{notice||t.ready}</span><span>{t.local}</span></footer></main>
}
