"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import JSZip from "jszip";
import { generateBundle, parseClashYaml, parseShareLinks, type InputKind, type ListenerType, type ParsedNode } from "@multiport/core";
type Lang="zh"|"en";
const text={
 zh:{privacy:"仅在本地处理",docs:"使用文档",eyebrow:"MIHOMO 配置生成器 · V0.2",headline:<>把节点变成<br/><em>清晰的本地端口。</em></>,intro:"将 Clash 配置或分享链接转换成“一节点一端口”的 Mihomo 配置，并同时生成 Chrome 扩展可导入的安全清单。密钥不会离开此浏览器。",input:"输入",inputSource:"输入源",links:"分享链接",yamlPlaceholder:"粘贴 Clash / Mihomo YAML 配置…",linksPlaceholder:"每行粘贴一个分享链接…",upload:"上传文件",demo:"使用示例",parse:"解析节点",map:"映射",selected:"已选择",startPort:"起始端口",host:"监听地址",listener:"监听类型",empty:"解析后的节点将在这里显示。",export:"导出",exportTitle:<>两个文件，<br/>同一份稳定映射。</>,exportIntro:"运行配置与浏览器档案使用相同顺序和端口。",yamlHelp:"包含节点和独立本地 listeners，可直接交给 Mihomo。",jsonHelp:"只包含本地端口映射，不包含上游 UUID 或密码。",copy:"复制",download:"下载",bundle:"下载完整压缩包",ready:"等待本地输入",local:"无遥测 · 无上传",loaded:"已载入",none:"未找到可用节点",read:"已读取",copied:"已复制"},
 en:{privacy:"Local-only processing",docs:"Documentation",eyebrow:"MIHOMO CONFIG FORGE · V0.2",headline:<>Turn nodes into<br/><em>clean local ports.</em></>,intro:"Convert Clash configurations or share links into one-node-per-port Mihomo listeners and a safe manifest for the Chrome extension. Secrets never leave this browser.",input:"Input",inputSource:"Source",links:"Share links",yamlPlaceholder:"Paste a Clash / Mihomo YAML config…",linksPlaceholder:"Paste one share link per line…",upload:"Upload file",demo:"Use demo",parse:"Parse nodes",map:"Map",selected:"selected",startPort:"Start port",host:"Listen host",listener:"Listener",empty:"Parsed nodes will appear here.",export:"Export",exportTitle:<>Two files.<br/>One stable map.</>,exportIntro:"The runtime config and browser profiles share the same order and ports.",yamlHelp:"Contains nodes and independent local listeners, ready for Mihomo.",jsonHelp:"Contains local port mappings only—never upstream UUIDs or passwords.",copy:"Copy",download:"Download",bundle:"Download complete bundle",ready:"Ready for local input",local:"No telemetry · No uploads",loaded:"Loaded",none:"No usable nodes found",read:"Read",copied:"copied"}
};
const DEMO=`proxies:\n  - name: Demo VLESS\n    type: vless\n    server: example.com\n    port: 443\n    uuid: 00000000-0000-0000-0000-000000000001\n    tls: true\n  - name: Demo SOCKS\n    type: socks5\n    server: 127.0.0.1\n    port: 1080`;
function save(name:string,data:BlobPart,type:string){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),0)}
export default function Home(){
 const [lang,setLang]=useState<Lang>("zh"),[kind,setKind]=useState<InputKind>("clash"),[source,setSource]=useState(""),[nodes,setNodes]=useState<ParsedNode[]>([]),[issues,setIssues]=useState<{line?:number;message:string}[]>([]),[selected,setSelected]=useState<Set<string>>(new Set()),[startPort,setStartPort]=useState(42000),[host,setHost]=useState("127.0.0.1"),[listenerType,setListenerType]=useState<ListenerType>("mixed"),[notice,setNotice]=useState("");
 const t=text[lang],fileRef=useRef<HTMLInputElement>(null),chosen=useMemo(()=>nodes.filter(n=>selected.has(n.id)),[nodes,selected]);
 useEffect(()=>{const saved=localStorage.getItem("portsmith-lang");if(saved==="en"||saved==="zh")setLang(saved);else if(navigator.language.toLowerCase().startsWith("en"))setLang("en")},[]);
 useEffect(()=>{document.documentElement.lang=lang==="zh"?"zh-CN":"en";localStorage.setItem("portsmith-lang",lang)},[lang]);
 const bundle=useMemo(()=>{try{return chosen.length?generateBundle(chosen,{startPort,host,listenerType}):null}catch{return null}},[chosen,startPort,host,listenerType]);
 function parseSource(value=source,nextKind=kind){const r=nextKind==="clash"?parseClashYaml(value):parseShareLinks(value);setNodes(r.nodes);setIssues(r.issues);setSelected(new Set(r.nodes.map(n=>n.id)));setNotice(r.nodes.length?`${t.loaded} ${r.nodes.length}`:t.none)}
 async function openFile(file?:File){if(!file)return;const value=await file.text();setSource(value);parseSource(value);setNotice(`${t.read} ${file.name}`)}
 async function copy(value:string,label:string){await navigator.clipboard.writeText(value);setNotice(`${label} ${t.copied}`)}
 async function zip(){if(!bundle)return;const z=new JSZip();z.file("mihomo.yaml",bundle.mihomoYaml);z.file("browser-profiles.json",JSON.stringify(bundle.extensionManifest,null,2));save("multiport-proxy-bundle.zip",await z.generateAsync({type:"blob"}),"application/zip")}
 return <main><header className="topbar"><a className="brand" href="#top"><b>P</b>PORTSMITH</a><div className="privacy"><i/>{t.privacy}</div><nav><div className="lang" aria-label="Language"><button className={lang==="zh"?"active":""} onClick={()=>setLang("zh")}>中文</button><button className={lang==="en"?"active":""} onClick={()=>setLang("en")}>EN</button></div><a className="docs" href={lang==="zh"?"https://github.com/":"https://github.com/"} target="_blank" rel="noreferrer">{t.docs} ↗</a></nav></header>
 <section className="hero" id="top"><div><p className="eyebrow">{t.eyebrow}</p><h1>{t.headline}</h1></div><p className="intro">{t.intro}</p></section>
 <section className="workspace"><div className="panel inputPanel"><div className="panelHead"><span>01 / {t.input}</span><span>{t.inputSource}</span></div><div className="tabs"><button className={kind==="clash"?"active":""} onClick={()=>setKind("clash")}>Clash YAML</button><button className={kind==="share-links"?"active":""} onClick={()=>setKind("share-links")}>{t.links}</button></div><textarea value={source} onChange={e=>setSource(e.target.value)} placeholder={kind==="clash"?t.yamlPlaceholder:t.linksPlaceholder} spellCheck={false}/><input ref={fileRef} hidden type="file" accept=".yaml,.yml,.txt" onChange={e=>void openFile(e.target.files?.[0])}/><div className="actions"><button onClick={()=>fileRef.current?.click()}>{t.upload}</button><button onClick={()=>{setKind("clash");setSource(DEMO);parseSource(DEMO,"clash")}}>{t.demo}</button><button className="primary" onClick={()=>parseSource()}>{t.parse} →</button></div>{issues.length>0&&<div className="issues" role="alert">{issues.slice(0,4).map((i,n)=><p key={n}>{i.line?`Line ${i.line}: `:""}{i.message}</p>)}</div>}</div>
 <div className="panel"><div className="panelHead"><span>02 / {t.map}</span><span>{chosen.length}/{nodes.length} {t.selected}</span></div><div className="controls"><label>{t.startPort}<input type="number" min="1" max="65535" value={startPort} onChange={e=>setStartPort(Number(e.target.value))}/></label><label>{t.host}<input value={host} onChange={e=>setHost(e.target.value)}/></label><label>{t.listener}<select value={listenerType} onChange={e=>setListenerType(e.target.value as ListenerType)}><option>mixed</option><option>http</option><option>socks</option></select></label></div><div className="nodeList">{!nodes.length&&<div className="empty">⌁<small>{t.empty}</small></div>}{nodes.map((node,index)=><label className="node" key={node.id}><input type="checkbox" checked={selected.has(node.id)} onChange={e=>{const next=new Set(selected);e.target.checked?next.add(node.id):next.delete(node.id);setSelected(next)}}/><span>{String(index+1).padStart(2,"0")}</span><strong>{node.name}<small>{node.type}</small></strong><code>{selected.has(node.id)?startPort+chosen.findIndex(n=>n.id===node.id):"—"}</code></label>)}</div></div></section>
 <section className="export"><div><span>03 / {t.export}</span><h2>{t.exportTitle}</h2><p>{t.exportIntro}</p></div><div><div className="cards"><article><b>YAML</b><h3>mihomo.yaml</h3><p>{t.yamlHelp}</p><div><button disabled={!bundle} onClick={()=>bundle&&void copy(bundle.mihomoYaml,"YAML")}>{t.copy}</button><button disabled={!bundle} onClick={()=>bundle&&save("mihomo.yaml",bundle.mihomoYaml,"text/yaml")}>{t.download} ↓</button></div></article><article><b>JSON</b><h3>browser-profiles.json</h3><p>{t.jsonHelp}</p><div><button disabled={!bundle} onClick={()=>bundle&&void copy(JSON.stringify(bundle.extensionManifest,null,2),"JSON")}>{t.copy}</button><button disabled={!bundle} onClick={()=>bundle&&save("browser-profiles.json",JSON.stringify(bundle.extensionManifest,null,2),"application/json")}>{t.download} ↓</button></div></article></div><button className="zip" disabled={!bundle} onClick={()=>void zip()}>{t.bundle}<span>.ZIP</span></button></div></section>
 <footer><span>PORTSMITH / OPEN SOURCE</span><span aria-live="polite">{notice||t.ready}</span><span>{t.local}</span></footer></main>}
