"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import JSZip from "jszip";
import {generateBundle,mergeParsedNodes,parseClashYaml,parseShareLinks,type ListenerType,type ParsedNode} from "@multiport/core";
type Lang="zh"|"en";
type Theme="light"|"dark";
const I={
zh:{privacy:"仅在浏览器本地处理",docs:"使用文档",eyebrow:"MIHOMO 多端口配置生成器 · V0.2",title:<>把代理节点变成<br/><em>清晰的本地端口。</em></>,intro:"将 Clash/Mihomo 配置或分享链接转换成“一节点一端口”的 Mihomo 配置，并生成 PortPilot 可导入的 HTTP 与 SOCKS5 档案。节点密钥不会离开此浏览器。",input:"输入",links:"节点分享链接",yp:"示例：\nproxies:\n  - name: 节点名称\n    type: vless\n    server: example.com\n    port: 443\n    uuid: ...",lp:"示例（每行一个节点）：\nvless://UUID@example.com:443?security=tls#节点名称\ntrojan://PASSWORD@example.com:443#节点名称",upload:"上传文件",demo:"使用示例",parse:"解析节点",map:"端口映射",selected:"个已选",start:"起始端口",host:"监听地址",listener:"监听类型",empty:"解析后，节点会显示在这里。",multi:"多端口监听",chain:"链式代理",jump:"跳板节点 B",exit:"出口节点 A",export:"导出",exportTitle:<>两个文件，<br/>一份稳定映射。</>,exportIntro:"Mihomo 配置与浏览器档案使用相同的节点顺序和端口。下载前可以直接阅读完整内容。",yamlHelp:"包含代理节点和独立本地 listeners，可直接交给 Mihomo。",jsonHelp:"只含本地端口映射，不包含上游 UUID、密码或服务器地址。",preview:"文件预览",previewEmpty:"解析并选择节点后显示完整内容",copy:"复制",download:"下载",bundle:"两个文件一起下载",ready:"等待本地输入",local:"无遥测 · 无上传",loaded:"已载入",none:"未找到可用节点",read:"已读取",copied:"已复制"},
en:{privacy:"Local-only browser processing",docs:"Documentation",eyebrow:"MIHOMO MULTI-PORT CONFIG FORGE · V0.2",title:<>Turn proxy nodes into<br/><em>clean local ports.</em></>,intro:"Convert Clash/Mihomo configurations or share links into one-node-per-port Mihomo listeners and HTTP/SOCKS5 profiles for PortPilot. Node secrets never leave this browser.",input:"Input",links:"Node share links",yp:"Example:\nproxies:\n  - name: Node name\n    type: vless\n    server: example.com\n    port: 443\n    uuid: ...",lp:"Example (one node per line):\nvless://UUID@example.com:443?security=tls#Node-name\ntrojan://PASSWORD@example.com:443#Node-name",upload:"Upload file",demo:"Use demo",parse:"Parse nodes",map:"Port map",selected:"selected",start:"Start port",host:"Listen host",listener:"Listener type",empty:"Parsed nodes will appear here.",multi:"Multi-port listeners",chain:"Dialer proxy",jump:"Jump node B",exit:"Exit node A",export:"Export",exportTitle:<>Two files.<br/>One stable map.</>,exportIntro:"The Mihomo configuration and browser profiles share the same node order and ports. Read the complete output before downloading.",yamlHelp:"Contains proxy nodes and independent local listeners, ready for Mihomo.",jsonHelp:"Contains local port mappings only—never upstream UUIDs, passwords, or server addresses.",preview:"File preview",previewEmpty:"Parse and select nodes to display the complete output",copy:"Copy",download:"Download",bundle:"Download both files",ready:"Ready for local input",local:"No telemetry · No uploads",loaded:"Loaded",none:"No usable nodes found",read:"Read",copied:"copied"}
} as const;
const DEMO=`proxies:\n  - name: Demo VLESS\n    type: vless\n    server: example.com\n    port: 443\n    uuid: 00000000-0000-0000-0000-000000000001\n    tls: true\n  - name: Demo SOCKS\n    type: socks5\n    server: 127.0.0.1\n    port: 1080`;
function save(name:string,data:BlobPart,type:string){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),0)}
function initialLanguage():Lang{if(typeof window==="undefined")return "zh";const saved=localStorage.getItem("multiport-language");if(saved==="zh"||saved==="en")return saved;return navigator.language.toLowerCase().startsWith("zh")?"zh":"en"}
function initialTheme():Theme{if(typeof window==="undefined")return "light";return localStorage.getItem("multiport-theme")==="dark"?"dark":"light"}
export default function Home(){
 const [lang,setLang]=useState<Lang>(initialLanguage),[theme,setTheme]=useState<Theme>(initialTheme),[yamlSource,setYamlSource]=useState(""),[linkSource,setLinkSource]=useState(""),[nodes,setNodes]=useState<ParsedNode[]>([]),[selected,setSelected]=useState<Set<string>>(new Set()),[issues,setIssues]=useState<{line?:number;message:string}[]>([]),[startPort,setStartPort]=useState(42000),[host,setHost]=useState("127.0.0.1"),[listenerType,setListenerType]=useState<ListenerType>("socks"),[baseConfig,setBaseConfig]=useState<Record<string,unknown>>(),[mode,setMode]=useState<"listeners"|"dialer-proxy">("listeners"),[jumpNodeId,setJumpNodeId]=useState(""),[exitNodeId,setExitNodeId]=useState(""),[notice,setNotice]=useState("");
 const fileRef=useRef<HTMLInputElement>(null),t=I[lang],chosen=useMemo(()=>nodes.filter(n=>selected.has(n.id)),[nodes,selected]);
 useEffect(()=>{document.documentElement.lang=lang==="zh"?"zh-CN":"en";localStorage.setItem("multiport-language",lang)},[lang]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem("multiport-theme",theme)},[theme]);
 const generation=useMemo(()=>{if(!chosen.length)return{bundle:null,error:""};try{return{bundle:generateBundle(chosen,{startPort,host,listenerType,baseConfig,mode,jumpNodeId,exitNodeId}),error:""}}catch(error){return{bundle:null,error:error instanceof Error?error.message:String(error)}}},[chosen,startPort,host,listenerType,baseConfig,mode,jumpNodeId,exitNodeId]),bundle=generation.bundle;
 useEffect(()=>{if(generation.error)setNotice(`${lang==="zh"?"无法生成文件":"Files cannot be generated"}: ${generation.error.replace(/^Cannot export:\s*/,"")}`)},[generation.error,lang]);
 function parseInputs(yamlValue=yamlSource,linksValue=linkSource){const y=yamlValue.trim()?parseClashYaml(yamlValue):{nodes:[],issues:[]},l=linksValue.trim()?parseShareLinks(linksValue):{nodes:[],issues:[]},merged=mergeParsedNodes(y.nodes,l.nodes);setNodes(merged);setBaseConfig(y.baseConfig);setIssues([...y.issues,...l.issues]);setSelected(new Set(merged.map(n=>n.id)));setJumpNodeId(merged[0]?.id||"");setExitNodeId(merged[1]?.id||"");setNotice(merged.length?`${t.loaded} ${merged.length}`:t.none)}
 async function openFile(file?:File){if(!file)return;const value=await file.text();setYamlSource(value);parseInputs(value,linkSource);setNotice(`${t.read} ${file.name}`)}
 async function copy(value:string,label:string){await navigator.clipboard.writeText(value);setNotice(`${label} ${t.copied}`)}
 async function zip(){if(!bundle)return;const z=new JSZip();z.file("mihomo.yaml",bundle.mihomoYaml);z.file("browser-profiles.json",JSON.stringify(bundle.extensionManifest,null,2));save("multiport-proxy-bundle.zip",await z.generateAsync({type:"blob"}),"application/zip")}
 return <main id="top"><header className="topbar"><a className="brand" href="#top"><b>M</b>MULTIPORT</a><div className="privacy"><i/>{t.privacy}</div><nav><button className="themeToggle" onClick={()=>setTheme(value=>value==="light"?"dark":"light")} aria-label={lang==="zh"?"切换明亮和深色主题":"Toggle light and dark theme"} aria-pressed={theme==="dark"}>{theme==="light"?"☀ ":"☾ "}{theme==="light"?(lang==="zh"?"明亮":"Light"):(lang==="zh"?"深色":"Dark")}</button><div className="lang"><button className={lang==="zh"?"active":""} onClick={()=>setLang("zh")}>中文</button><button className={lang==="en"?"active":""} onClick={()=>setLang("en")}>EN</button></div><a className="docs" href={lang==="zh"?"https://github.com/huades/MultiPort-Proxy/blob/main/README.zh-CN.md":"https://github.com/huades/MultiPort-Proxy#readme"} target="_blank" rel="noreferrer">{t.docs} ↗</a></nav></header>
 <section className="hero"><div><p className="eyebrow">{t.eyebrow}</p><h1>{t.title}</h1></div><div className="heroAside"><p className="intro">{t.intro}</p><a href="#converter" className="startLink">{lang==="zh"?"开始转换":"Start converting"} ↓</a></div></section>
 <section className="flow" aria-label={lang==="zh"?"使用流程":"Workflow"}><article><span>01</span><div><b>{lang==="zh"?"粘贴节点":"Paste nodes"}</b><p>{lang==="zh"?"输入本地 YAML 或分享链接，不读取远程订阅。":"Use local YAML or share links. Remote subscriptions are never fetched."}</p></div></article><article><span>02</span><div><b>{lang==="zh"?"检查映射":"Review mapping"}</b><p>{lang==="zh"?"选择节点，确认一节点一端口及监听协议。":"Select nodes and confirm each local port and listener protocol."}</p></div></article><article><span>03</span><div><b>{lang==="zh"?"导出 Mihomo YAML":"Export Mihomo YAML"}</b><p>{lang==="zh"?"预览并下载运行配置，交给 Mihomo 启动。":"Review and download the runtime configuration for Mihomo."}</p></div></article><article><span>04</span><div><b>{lang==="zh"?"导出插件 JSON":"Export extension JSON"}</b><p>{lang==="zh"?"下载本地端口档案，再导入 PortPilot。":"Download the local port profiles and import them into PortPilot."}</p></div></article></section>
 <section className="workspace" id="converter"><div className="panel inputPanel"><div className="panelHead"><span>01 / {t.input}</span><span>YAML + URI</span></div><div className="sourceBlocks"><section className="sourceBlock"><div className="sourceTitle"><b>Clash YAML</b><span>{lang==="zh"?"可选基础配置":"Optional base config"}</span></div><p className="inputHint">{lang==="zh"?"上传或粘贴包含 proxies: 的 Clash/Mihomo YAML。已有配置和节点字段会保留。":"Upload or paste Clash/Mihomo YAML containing proxies:. Existing configuration and proxy fields are preserved."}</p><textarea value={yamlSource} onChange={e=>setYamlSource(e.target.value)} placeholder={t.yp} spellCheck={false}/><div className="actions"><button onClick={()=>fileRef.current?.click()}>{t.upload}</button><button onClick={()=>{setYamlSource(DEMO);parseInputs(DEMO,linkSource)}}>{t.demo}</button></div></section><section className="sourceBlock"><div className="sourceTitle"><b>{t.links}</b><span>{lang==="zh"?"追加到 YAML":"Append to YAML"}</span></div><p className="inputHint">{lang==="zh"?"每行一个分享链接；会与上方 YAML 节点合并。只填这里也会生成标准 Clash/Mihomo YAML。":"One share link per line. These nodes are merged with the YAML above. Using only this field still produces standard Clash/Mihomo YAML."}</p><textarea value={linkSource} onChange={e=>setLinkSource(e.target.value)} placeholder={t.lp} spellCheck={false}/><div className="actions"><button className="primary" onClick={()=>parseInputs()}>{lang==="zh"?"解析并合并":"Parse and merge"} →</button></div></section></div><input ref={fileRef} hidden type="file" accept=".yaml,.yml,.txt" onChange={e=>void openFile(e.target.files?.[0])}/>{issues.length>0&&<div className="issues" role="alert">{issues.slice(0,8).map((x,i)=><p key={i}>{x.line?`Line ${x.line}: `:""}{x.message}</p>)}</div>}</div>
 <div className="panel"><div className="panelHead"><span>02 / {t.map}</span><span>{chosen.length}/{nodes.length} {t.selected}</span></div><div className="modeSwitch"><button className={mode==="listeners"?"active":""} onClick={()=>setMode("listeners")}>{t.multi}</button><button className={mode==="dialer-proxy"?"active":""} onClick={()=>setMode("dialer-proxy")}>{t.chain}</button></div>{mode==="listeners"?<div className="controls"><label>{t.start}<input type="number" min="1" max="65535" value={startPort} onChange={e=>setStartPort(Number(e.target.value))}/></label><label>{t.host}<input value={host} onChange={e=>setHost(e.target.value)}/></label><label>{t.listener}<select value={listenerType} onChange={e=>setListenerType(e.target.value as ListenerType)}><option value="socks">SOCKS5</option><option value="mixed">mixed</option><option value="http">HTTP</option></select></label></div>:<div className="chainControls"><label>{t.jump}<select value={jumpNodeId} onChange={e=>setJumpNodeId(e.target.value)}>{chosen.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></label><span>→</span><label>{t.exit}<select value={exitNodeId} onChange={e=>setExitNodeId(e.target.value)}>{chosen.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></label></div>}<div className="nodeList">{!nodes.length&&<div className="empty">◎<small>{t.empty}</small></div>}{nodes.map((n,i)=><label className="node" key={n.id}><input type="checkbox" checked={selected.has(n.id)} onChange={e=>{const v=new Set(selected);if(e.target.checked)v.add(n.id);else v.delete(n.id);setSelected(v)}}/><span>{String(i+1).padStart(2,"0")}</span><strong>{n.name}<small>{n.type}</small></strong><code>{mode==="listeners"&&selected.has(n.id)?startPort+chosen.findIndex(x=>x.id===n.id):"—"}</code></label>)}</div></div></section>
 <section className="export"><div className="exportIntro"><span>{lang==="zh"?"按顺序检查并导出":"Review and export in order"}</span><h2>{t.exportTitle}</h2><p>{t.exportIntro}</p></div><section className="exportStage yamlStage"><div className="stageInfo"><span>03 / MIHOMO YAML</span><h3>mihomo.yaml</h3><p>{t.yamlHelp}</p><div className="formatNotice"><b>{lang==="zh"?"这是当前格式的配置快照":"A snapshot of the current format"}</b><small>{lang==="zh"?"请保留原始 YAML 或分享链接。Mihomo 或节点格式变化后，用原始内容重新生成，不要把本文件当作永久节点源。":"Keep the original YAML or share links. If Mihomo or node formats change, regenerate from the original input instead of treating this file as a permanent node source."}</small></div><div className="stageActions"><button disabled={!bundle} onClick={()=>bundle&&void copy(bundle.mihomoYaml,"YAML")}>{t.copy}</button><button disabled={!bundle} onClick={()=>bundle&&save("mihomo.yaml",bundle.mihomoYaml,"text/yaml")}>{t.download} YAML →</button></div></div><div className="stagePreview"><header><b>YAML</b><span>{t.preview} · mihomo.yaml</span></header><pre><code>{bundle?.mihomoYaml||t.previewEmpty}</code></pre></div></section><section className="exportStage jsonStage"><div className="stageInfo"><span>04 / PORTPILOT JSON</span><h3>browser-profiles.json</h3><p>{t.jsonHelp}</p><div className="formatNotice safe"><b>{lang==="zh"?"只记录本机代理入口":"Local proxy entries only"}</b><small>{lang==="zh"?"JSON 不保存上游节点密钥；Mihomo 端口变化后需要重新导出并导入 PortPilot。":"The JSON excludes upstream credentials. Export and import it again whenever the Mihomo ports change."}</small></div><div className="stageActions"><button disabled={!bundle} onClick={()=>bundle&&void copy(JSON.stringify(bundle.extensionManifest,null,2),"JSON")}>{t.copy}</button><button disabled={!bundle} onClick={()=>bundle&&save("browser-profiles.json",JSON.stringify(bundle.extensionManifest,null,2),"application/json")}>{t.download} JSON →</button></div></div><div className="stagePreview"><header><b>JSON</b><span>{t.preview} · browser-profiles.json</span></header><pre><code>{bundle?JSON.stringify(bundle.extensionManifest,null,2):t.previewEmpty}</code></pre></div></section><div className="bundleBar"><div><b>{lang==="zh"?"需要两个文件？":"Need both files?"}</b><small>{lang==="zh"?"ZIP 内同时包含 Mihomo YAML 与 PortPilot JSON。":"The ZIP contains the Mihomo YAML and PortPilot JSON."}</small></div><button className="zip" disabled={!bundle} onClick={()=>void zip()}>{t.bundle}<span>.ZIP</span></button></div></section>
 {generation.error&&<div className="generationError" role="alert"><b>{lang==="zh"?"无法生成 YAML 和 JSON":"YAML and JSON cannot be generated"}</b><span>{generation.error.replace(/^Cannot export:\s*/,"")}</span><small>{lang==="zh"?"请取消选择有问题的节点，或补齐原始 YAML/分享链接中的必填字段。":"Deselect the invalid node or complete its required source fields."}</small></div>}<footer><span>MULTIPORT-PROXY / OPEN SOURCE</span><span aria-live="polite">{notice||t.ready}</span><span>{t.local}</span></footer></main>
}
